server:
  port: 8187

# Oracle Connect
spring:
  config:
    import: optional:classpath:application-aws.yml

  # aws
  profiles:
    include: aws


  datasource:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    url: jdbc:oracle:thin:@localhost:1521/xe
    username: test240716
    password: oracle240716

  # view Resolver
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB

# Mybatis
mybatis:
  config-location: classpath:configuration.xml
  mapper-locations: classpath:mappers/*.xml

logging.level:
  org.hibernate.SQL: debug   # logger를 통해 하이버네이트 실행 SQL